<?php


namespace Modules\Admin\Posts\Repositories;

use Core\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Model;
use Modules\Admin\Posts\Models\Post;

class PostsRepository extends BaseRepository implements PostsInterface
{
    /**
     * PostRepository constructor.
     *
     * @param Post $post
     */
    public function __construct(Post $post)
    {
        parent::__construct($post);
        $this->model = $post;
    }

    public function index(int $perPage = 10)
    {
        return parent::index($perPage); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes): Post
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function read($id): Model
    {
        return parent::read($id); // TODO: Change the autogenerated stub
    }

    public function update(array $data, string $id): bool
    {
        return parent::update($data, $id); // TODO: Change the autogenerated stub
    }

    public function delete(string $id): bool
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

}
